services:
  - type: web
    name: yaafo-laravel
    env: php
    plan: free
    region: oregon

    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build

    startCommand: php artisan serve --host=0.0.0.0 --port=10000

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:Ta_clef_app # remplace par ta vraie clé (ou laisse artisan la générer)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql8.freesqldatabase.com
      - key: DB_PORT
        value: '3306'
      - key: DB_DATABASE
        value: sql8790689
      - key: DB_USERNAME
        value: sql8790689
      - key: DB_PASSWORD
        value: QSVwLDegVY
